use std::io::{self, BufReader, ErrorKind, Read};
use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::sync::mpsc::Sender;
use std::sync::Arc;

pub fn freshclam_conf_contents(db_dir: &Path) -> String {
    format!(
        "# Generated by ClamAV UI. Custom options (e.g. HTTPProxyServer) may be added below.\n\
         DatabaseMirror database.clamav.net\n\
         DatabaseDirectory \"{}\"\n",
        db_dir.display()
    )
}

/// Write the config only when it does not exist yet, so user edits survive.
pub fn ensure_freshclam_conf(conf_path: &Path, db_dir: &Path) -> io::Result<()> {
    if conf_path.is_file() {
        return Ok(());
    }
    if let Some(parent) = conf_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(conf_path, freshclam_conf_contents(db_dir))
}

/// Read a stream and emit a line at every `\n` or `\r`, so freshclam's progress updates stream live.
pub fn read_lines_cr<R: Read>(reader: R, mut on_line: impl FnMut(String)) {
    let mut reader = BufReader::new(reader);
    let mut buf: Vec<u8> = Vec::new();
    let mut byte = [0u8; 1];
    loop {
        match reader.read(&mut byte) {
            Ok(0) => break,
            Ok(_) => {
                if byte[0] == b'\n' || byte[0] == b'\r' {
                    if !buf.is_empty() {
                        on_line(String::from_utf8_lossy(&buf).into_owned());
                        buf.clear();
                    }
                } else {
                    buf.push(byte[0]);
                }
            }
            Err(e) if e.kind() == ErrorKind::Interrupted => continue,
            Err(_) => break,
        }
    }
    if !buf.is_empty() {
        on_line(String::from_utf8_lossy(&buf).into_owned());
    }
}

#[derive(Debug)]
pub enum UpdateEvent {
    Started,
    Line(String),
    Finished { exit_code: Option<i32> },
    SpawnFailed(String),
}

/// Spawn freshclam in a worker thread. stdout and stderr both stream as `Line` events.
pub fn start_update(
    freshclam: PathBuf,
    conf: PathBuf,
    db_dir: PathBuf,
    tx: Sender<UpdateEvent>,
    notify: impl Fn() + Send + Sync + 'static,
) {
    let notify: Arc<dyn Fn() + Send + Sync> = Arc::new(notify);
    std::thread::spawn(move || {
        let send = |ev: UpdateEvent| {
            let _ = tx.send(ev);
            notify();
        };
        let mut cmd = crate::engine::quiet_command(&freshclam);
        cmd.arg(format!("--config-file={}", conf.display()))
            .arg(format!("--datadir={}", db_dir.display()))
            .arg("--stdout")
            .stdin(Stdio::null())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped());
        let mut child = match cmd.spawn() {
            Ok(c) => c,
            Err(e) => {
                send(UpdateEvent::SpawnFailed(format!("{}: {e}", freshclam.display())));
                return;
            }
        };
        let stdout = child.stdout.take().expect("stdout is piped");
        let stderr = child.stderr.take().expect("stderr is piped");
        send(UpdateEvent::Started);

        let stderr_thread = {
            let tx = tx.clone();
            let notify = Arc::clone(&notify);
            std::thread::spawn(move || {
                read_lines_cr(stderr, |line| {
                    let _ = tx.send(UpdateEvent::Line(line));
                    notify();
                });
            })
        };
        read_lines_cr(stdout, |line| send(UpdateEvent::Line(line)));
        let _ = stderr_thread.join();

        match child.wait() {
            Ok(status) => send(UpdateEvent::Finished { exit_code: status.code() }),
            Err(e) => send(UpdateEvent::SpawnFailed(format!("Warten auf freshclam fehlgeschlagen: {e}"))),
        }
    });
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Cursor;

    #[test]
    fn conf_contains_mirror_and_db_dir() {
        let text = freshclam_conf_contents(Path::new("/home/me/.local/share/clamavui/db"));
        assert!(text.contains("DatabaseMirror database.clamav.net\n"));
        assert!(text.contains("DatabaseDirectory \"/home/me/.local/share/clamavui/db\"\n"));
    }

    #[test]
    fn ensure_conf_writes_when_missing_and_keeps_existing() {
        let dir = tempfile::tempdir().unwrap();
        let conf = dir.path().join("cfg").join("freshclam.conf");
        ensure_freshclam_conf(&conf, Path::new("/db")).unwrap();
        assert!(std::fs::read_to_string(&conf).unwrap().contains("DatabaseDirectory \"/db\""));

        std::fs::write(&conf, "HTTPProxyServer proxy.local\n").unwrap();
        ensure_freshclam_conf(&conf, Path::new("/db")).unwrap();
        assert_eq!(std::fs::read_to_string(&conf).unwrap(), "HTTPProxyServer proxy.local\n");
    }

    #[test]
    fn read_lines_cr_splits_on_cr_and_lf() {
        let mut lines = Vec::new();
        read_lines_cr(Cursor::new("a\r\nDownloading daily.cvd [ 10%]\rDownloading daily.cvd [ 20%]\nend"), |l| lines.push(l));
        assert_eq!(
            lines,
            vec!["a", "Downloading daily.cvd [ 10%]", "Downloading daily.cvd [ 20%]", "end"]
        );
    }

    #[test]
    fn read_lines_cr_handles_empty_input() {
        let mut lines = Vec::new();
        read_lines_cr(Cursor::new(""), |l| lines.push(l));
        assert!(lines.is_empty());
    }

    #[test]
    #[cfg(unix)]
    fn worker_streams_stdout_and_finishes() {
        let _guard = crate::engine::test_support::exec_lock();
        use std::os::unix::fs::PermissionsExt;
        use std::sync::mpsc;
        use std::time::Duration;

        let dir = tempfile::tempdir().unwrap();
        let script = dir.path().join("script.sh");
        std::fs::write(&script, "#!/bin/sh\nprintf 'Downloading daily.cvd [ 50%%]\\rDownloading daily.cvd [100%%]\\n'; echo 'done' >&2; exit 0\n").unwrap();
        std::fs::set_permissions(&script, std::fs::Permissions::from_mode(0o755)).unwrap();

        let (tx, rx) = mpsc::channel();
        start_update(
            script,
            PathBuf::from("/conf"),
            PathBuf::from("/db"),
            tx,
            || {},
        );

        let mut events = Vec::new();
        loop {
            match rx.recv_timeout(Duration::from_secs(10)) {
                Ok(ev) => {
                    let is_terminal = matches!(ev, UpdateEvent::Finished { .. } | UpdateEvent::SpawnFailed(..));
                    events.push(ev);
                    if is_terminal {
                        break;
                    }
                }
                Err(_) => panic!("timeout waiting for events"),
            }
        }

        assert!(!events.is_empty());
        assert!(matches!(events[0], UpdateEvent::Started));

        let lines: Vec<String> = events
            .iter()
            .filter_map(|ev| {
                if let UpdateEvent::Line(l) = ev {
                    Some(l.clone())
                } else {
                    None
                }
            })
            .collect();

        assert!(lines.iter().any(|l| l.contains("Downloading daily.cvd [ 50%]")));
        assert!(lines.iter().any(|l| l.contains("Downloading daily.cvd [100%]")));
        assert!(lines.iter().any(|l| l.contains("done")));

        assert!(matches!(events.last(), Some(UpdateEvent::Finished { exit_code: Some(0) })));
    }

    #[test]
    fn spawn_failure_reports_spawn_failed() {
        let _guard = crate::engine::test_support::exec_lock();
        use std::sync::mpsc;
        use std::time::Duration;

        let (tx, rx) = mpsc::channel();
        start_update(
            PathBuf::from("/nonexistent/binary"),
            PathBuf::from("/conf"),
            PathBuf::from("/db"),
            tx,
            || {},
        );

        match rx.recv_timeout(Duration::from_secs(5)) {
            Ok(UpdateEvent::SpawnFailed(_)) => {
                // Expected
            }
            other => panic!("expected SpawnFailed, got: {:?}", other),
        }
    }
}
